import nodemailer from 'nodemailer';
import puppeteer from 'puppeteer';
import { getMailConfig } from './appConfig.js';

let transporter;

function getTransporter() {
  if (!transporter) {
    const config = getMailConfig();
    transporter = nodemailer.createTransport({
      service: config.service,
      auth: {
        user: config.user,
        pass: config.pass,
      },
    });
  }

  return transporter;
}
const htmlToPdfBuffer = async (html) => {
  const browser = await puppeteer.launch({ headless: "new" });
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });
  const pdf = await page.pdf({ format: 'A4', margin: { top: '8mm', bottom: '8mm' } });
  await browser.close();
  return pdf;
};


export const sendMail = async (email, data) => {
  const config = getMailConfig();
  const htmlBody = generateEmail(data);
  // const pdfBuffer = await htmlToPdfBuffer(htmlBody);
  console.log("123456789", data)
  return getTransporter().sendMail({
    from: config.from || config.user,
    to: email,
    subject: "Hello",
    text: "Working!",
    html: htmlBody
    // attachments: [{filename: 'weibo_report.pdf',content: pdfBuffer}]
    // attachments: [{filename: 'weibo_report.pdf',content: pdfBuffer}]

  });
}

const SENTIMENT_KEYS = ["POS", "NEG", "MIXED", "UNKNOWN"];

function buildSentimentStats(comments) {
  const counts = { POS: 0, NEG: 0, MIXED: 0, UNKNOWN: 0 };

  comments.forEach((comment) => {
    const sentiment = SENTIMENT_KEYS.includes(comment.sentiment) ? comment.sentiment : "UNKNOWN";
    counts[sentiment] += comment.freq ?? 0;
  });

  const total = Object.values(counts).reduce((sum, value) => sum + value, 0);
  return { total, counts };
}

const generateEmail = (data) => {
  const stats = buildSentimentStats(data.comments);

  const top5 = data.top_comments;
  const duplicatedComments = data.comments.filter((comment) => (comment.freq ?? 0) >= 3);
  const top5tableRows=top5.map(item => `
  <tr>
    <td>${item.comment}</td>
    <td>${item.freq || item.like_count}</td>
    <td>${item.sentiment}</td>
  </tr>
`).join(''); // The .join('') is crucial here

  const top10NegMixed = data.comments.filter(c => c.sentiment != 'POS');
  let top10tableRows;
  if (top10NegMixed.length > 0){
    top10tableRows = top10NegMixed.map((item => `
    <tr>
      <td>${item.comment}</td>
      <td>${item.freq || item.like_count}</td>
      <td>${item.sentiment}</td>
    </tr>
    `)).join('')}
   else {
    top10tableRows = `<tr><td colspan="3">(none)</td></tr>`
  }

  const duplicatedCommentRows = duplicatedComments.length > 0
    ? duplicatedComments.map((item) => `
    <tr>
      <td>${item.comment}</td>
      <td>${item.freq || item.like_count}</td>
      <td>${item.sentiment || "UNKNOWN"}</td>
    </tr>
    `).join('')
    : `<tr><td colspan="3">(none)</td></tr>`;

  return `
    <html>
      <body style="font-family: sans-serif; line-height: 1.6; color: #333;">
        <h1>Weibo Report: ${data.url}</h1>
        <p><strong>Date:</strong> ${new Date(data.date).toLocaleDateString()}</p>

        <h2>Current Summary Statistics 当前可见评论统计</h2>
        <ul>
          <li>Visible total: ${stats.total}</li>
          <li>当前可见评论总数： ${stats.total}</li>
          <li>POS(正面) ${stats.counts.POS}</li>
          <li>NEG(负面) ${stats.counts.NEG}</li>
          <li>MIXED(中性) ${stats.counts.MIXED}</li>
          <li>UNKNOWN(未评) ${stats.counts.UNKNOWN}</li>
        </ul>

        <h2>Top 5 Trending Comments</h2>
        <table border="1" cellPadding="8" style={{ borderCollapse: 'collapse', width: '100%' }}>
          <thead>
            <tr>
              <th>Comment</th>
              <th>Freq</th>
              <th>Sentiment</th>
            </tr>
          </thead>
          <tbody>
            ${top5tableRows}
          </tbody>
        </table>

        <h2>Top duplicated Comments</h2>
        <table border="1" cellPadding="8" style={{ borderCollapse: 'collapse', width: '100%' }}>
          <thead>
            <tr>
              <th>Comment</th>
              <th>Freq</th>
              <th>Sentiment</th>
            </tr>
          </thead>
          <tbody>
            ${duplicatedCommentRows}
          </tbody>
        </table>

        <h2>Top 10 Negative / Mixed Comments</h2>
        <table border="1" cellPadding="8" style={{ borderCollapse: 'collapse', width: '100%' }}>
          <thead>
            <tr>
              <th>Comment</th>
              <th>Freq</th>
              <th>Sentiment</th>
            </tr>
          </thead>
          <tbody>
            ${top10tableRows}
          </tbody>
        </table>


        <h2>Keywords Analysis</h2>
        ${data.summary.keywords.map(k => `
          <h3>${k.keyword}</h3>
          <ul>${k.supporting_comments.map(s => `<li>${s}</li>`).join('')}</ul>
        `).join('')}

        <p><em>${data.summary.summary}</em></p>

        <hr>
        <footer style="font-size: 0.8em; color: #777;">
          Generated by weibo comment monitor system
        </footer>
      </body>
    </html>
  `;
};


