import nodemailer from 'nodemailer';
import puppeteer from 'puppeteer';

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "williamma621@gmail.com",
    pass: "mocp viui phxq skyr",
  },
});
const htmlToPdfBuffer = async (html) => {
  const browser = await puppeteer.launch({ headless: "new" });
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });
  const pdf = await page.pdf({ format: 'A4', margin: { top: '8mm', bottom: '8mm' } });
  await browser.close();
  return pdf;
};


export const sendMail = (email, data) => {
  const htmlBody = generateEmail(data);
  // const pdfBuffer = await htmlToPdfBuffer(htmlBody);
  console.log("123456789", data)
  transporter.sendMail({
    from: "williamma621@gmail.com",
    to: email,
    subject: "Hello",
    text: "Working!",
    html: htmlBody
    // attachments: [{filename: 'weibo_report.pdf',content: pdfBuffer}]

  });
}

const generateEmail = (data) => {
  // 1. Calculate Summary Statistics
  const stats = data.comments.reduce((acc, c) => {
    acc.total += 1;
    acc[c.sentiment] = (acc[c.sentiment] || 0) + 1;
    return acc;
  }, { total: 0, POS: 0, NEG: 0, MIXED: 0 });

  // 2. Extract specific lists
  const top5 = data.comments.slice(0, 5);
  const top5tableRows=top5.map(item => `
  <tr>
    <td>${item.comment}</td>
    <td>${item.freq || item.like_count}</td>
    <td>${item.sentiment}</td>
  </tr>
`).join(''); // The .join('') is crucial here

  const top10NegMixed = data.comments.filter(c => c.sentiment != 'POS');
  console.log(top10NegMixed)
  console.log(top10NegMixed.length == 0)
  let top10tableRows;
  if (top10NegMixed){
    top10tableRows = top10NegMixed.map((item => `
    <tr>
      <td>${item.comment}</td>
      <td>${item.freq || item.like_count}</td>
      <td>${item.sentiment}</td>
    </tr>
    `)).join('')}
   else {
    top10tableRows = `<p>(none)</p>`
  }
  

  // 3. HTML Template
  return `
    <html>
      <body style="font-family: sans-serif; line-height: 1.6; color: #333;">
        <h1>Weibo Report: ${data.url}</h1>
        <p><strong>Date:</strong> ${new Date(data.date).toLocaleDateString()}</p>

        <h2>Current Summary Statistics 当前可见评论统计</h2>
        <ul>
          <li> Total (当前可见评论总量) ${stats.total}</li>
          <li> POS(正面) ${stats.POS}</li>
          <li> NEG(负面) ${stats.NEG}</li>
          <li> MIXED(中性) ${stats.MIXED}</li>
        </ul>

        <h2>Top 5 Trending Comments</h2>
        <table border="1" cellPadding="8" style={{ borderCollapse: 'collapse', width: '100%' }}>
          <thead>
            <tr>
              <th>Comment</th>
              <th>Freq</th>
              <th>Sentiment</th>
            </tr>
          </thead>
          <tbody>
            ${top5tableRows}
          </tbody>
        </table>

        <h2>Top 10 Negative / Mixed Comments</h2>
        <table border="1" cellPadding="8" style={{ borderCollapse: 'collapse', width: '100%' }}>
          <thead>
            <tr>
              <th>Comment</th>
              <th>Freq</th>
              <th>Sentiment</th>
            </tr>
          </thead>
          <tbody>
            ${top10tableRows}
          </tbody>
        </table>


        <h2>Keywords Analysis</h2>
        ${data.summary.keywords.map(k => `
          <h3>${k.keyword}</h3>
          <ul>${k.supporting_comments.map(s => `<li>${s}</li>`).join('')}</ul>
        `).join('')}

        <p><em>${data.summary.summary}</em></p>

        <hr>
        <footer style="font-size: 0.8em; color: #777;">
          Generated by weibo comment monitor system
        </footer>
      </body>
    </html>
  `;
};


